apiVersion: v1
kind: ReplicationController
metadata:  
    name: flask-rc
    labels:
        app: flask
spec:
    replicas: 4
    selector:
        app: flask  
    template:    
        metadata:      
            labels:        
                app: flask    
        spec:      
            containers:      
            - name: flask-container        
              image: swetha0009/your-flask-app:latest
              ports:        
              - containerPort: 5000
              env:
              - name: MONGO_HOST
                value: mongo-db-service
              - name: MONGO_PORT
                value: "27017"
