apiVersion: v1
kind: Pod
metadata:  
    name: mongodb
spec:  
    containers:  
    - name: mongodb    
      image: mongo    
      ports:    
      - containerPort: 27017    
      volumeMounts:    
      - mountPath: /data/db      
        name: mongodb-storage  
    volumes:  
    - name: mongodb-storage    
      persistentVolumeClaim:      
        claimName: mongodb-pvc
